services:
  bot:
    build: .
    container_name: nsldai-bot-prod
    restart: unless-stopped
    volumes:
      - ./database.db:/app/database.db
      - ./phantom_history.db:/app/phantom_history.db
      - ./phantom_userbot.session:/app/phantom_userbot.session
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
