services:
  bot:
    build: .
    container_name: nsldai-bot-prod
    restart: unless-stopped
    volumes:
      - .:/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
